In [1]:
import requests
import json
import pandas as pd
import csv

response_API = requests.get('https://myvaccination-backend.vercel.app/api/vacc_reg')
data = response_API.text
dic = json.loads(data)
dic = dic['modifiedData']
df = pd.DataFrame(dic)
df

,date,totalAll,totalPhase2,platform_mysj,platform_call,platform_web,demographic_children,demographic_elderly,demographic_comorb,demographic_disabled
0,2021-06-24,16191488,5219793,14910368,10668,1270452,0,2787690,3938517,298917
1,2021-06-25,16321185,5253580,15031571,10779,1278835,0,2802744,3964444,301849
2,2021-06-26,16431724,5282795,15136062,10892,1284770,0,2815665,3986607,304571
3,2021-06-27,16515196,5304420,15231554,10808,1272834,0,2824735,4003420,306740
4,2021-06-28,16630764,5333905,15335726,10933,1284105,0,2835474,4027560,309623
...,...,...,...,...,...,...,...,...,...,...
254,2022-03-05,26795200,7020546,25664686,10313,1120201,1218074,3423464,5156009,640289
255,2022-03-06,26809324,7021840,25679039,10309,1119976,1229084,3423669,5156911,640582
256,2022-03-07,26822482,7023156,25692413,10305,1119764,1239108,3423882,5157899,640806
257,2022-03-08,26836366,7024405,25706560,10302,1119504,1249229,3424096,5158760,641074
258,2022-03-09,26850478,7025788,25720904,10301,1119273,1259743,3424309,5159777,641346

In [2]:
df.to_csv('vaccination.csv',index=False)

In [3]:
!pip install pymongo
from pymongo import MongoClient
client = MongoClient("mongodb+srv://madihahzabri:admin@newcluster.rh45owl.mongodb.net/test");

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pymongo in c:\users\madih\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (4.3.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\madih\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pymongo) (2.3.0)

In [4]:
import csv
import pymongo

# Connect to MongoDB
client = pymongo.MongoClient('mongodb+srv://madihahzabri:admin@newcluster.rh45owl.mongodb.net/test')
db = client['vaccination']
collection = db['vaccination']

# Open CSV file and read data
with open('vaccination.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    # Iterate through each row of the CSV file and insert it into MongoDB
    for row in reader:
        collection.insert_one(row)
        
print('CSV data uploaded to MongoDB successfully.')

CSV data uploaded to MongoDB successfully.