<a href="https://colab.research.google.com/github/drshahizan/special-topic-data-engineering/blob/main/assignment/data-scraping/submission/part2/Rivertion/ASGN_P2_Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install google-search-results

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting google-search-results
  Downloading google_search_results-2.4.2.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from google-search-results) (2.27.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->google-search-results) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->google-search-results) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->google-search-results) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->google-search-results) (3.4)
Building wheels for collected packages: google-search-results
  Building wheel for google-search-results (setup.py) ... done
  Created wheel for google-search-results: filename=google_search_results-2.4.2-py3-none-any.whl size=32019 sha256=ca97b90cd142d3bda242d5ee4405f55f83ff6aab27b3fb10c31877320b86d9d2
  Stored in directory: /root/.cache/pip/wheels/d3/b2/c3/03302d12bb44a2cdff3c9371f31b72c0c4e84b8d2285eeac53
Successfully built google-search-results
Installing collected packages: google-search-results
Successfully installed google-search-results-2.4.2

# Scraping 1 profile

In [ ]:
from serpapi import GoogleSearch

params = {
  "engine": "google_scholar_author",
  "author_id": "QzgVq24AAAAJ",  #Author ID for Mohd Shahizan Othman
  "num": 100,
  "api_key": "f2f8a14b58b97ce43b6861d726c878c830513380d64c846423a1814b133b25cb"
}

search = GoogleSearch(params)
results = search.get_dict()
author = results["author"]

In [ ]:
data = []
for response in results['articles']:
    title = response['title']
    author = response['authors']
    # pub_info = response['publication_info']
    # journal = response['journal']
    year = response['year']
    citations = response['cited_by']
    
    data.append({
        'Title': title,
        'Author': author,
        # 'Publication Info': pub_info,
        # 'Journal': journal,
        'Year': year,
        'Citations': citations
    })

In [ ]:
df = pd.DataFrame(data)
# df.to_csv('google_scholar_data.csv', index=False)
df

,Title,Author,Year,Citations
0,The impact of social media use on academic per...,"W Al-Rahmi, M Othman",2013,"{'value': 317, 'link': 'https://scholar.google..."
1,The improvement of students' academic performa...,"WM Al-Rahmi, MS Othman, MA Musa",2014,"{'value': 240, 'link': 'https://scholar.google..."
2,A model of factors affecting learning performa...,"WM Al-Rahmi, N Alias, MS Othman, VI Marin, G Tur",2018,"{'value': 231, 'link': 'https://scholar.google..."
3,The role of social media for collaborative lea...,"W Al-Rahmi, MS Othman, LM Yusuf",2015,"{'value': 199, 'link': 'https://scholar.google..."
4,Use of e-learning by university students in Ma...,"WM Al-Rahmi, N Alias, MS Othman, AI Alzahrani,...",2018,"{'value': 187, 'link': 'https://scholar.google..."
...,...,...,...,...
95,Enterprise ontology based knowledge map for im...,"MA Musa, MS Othman, WM Al-Rahimi",2013,"{'value': 3, 'link': 'https://scholar.google.c..."
96,The parallel AGE variances method for temperat...,"LM Yusuf, N Alias, MSB Ghouse, SM Shamsuddin, ...",2011,"{'value': 3, 'link': 'https://scholar.google.c..."
97,Integrated approach to knowledge management in...,"J Salim, M Mohd, M Othman",2011,"{'value': 3, 'link': 'https://scholar.google.c..."
98,Improving utility accrual scheduling algorithm...,"I Ahmad, M Othman, Z Zulkarnain, MF Othman",2008,"{'value': 3, 'link': 'https://scholar.google.c..."
99,Pembangunan Apilikasi Web Menggunakan Active S...,"MS Othman, S Miskon, SNHS Abdullah, LM Yusuf",2006,"{'value': 3, 'link': 'https://scholar.google.c..."

# Scraping all UTM FoC Staff

In [ ]:
from serpapi import GoogleSearch
from urllib.parse import urlsplit, parse_qsl

params = {
  "engine": "google_scholar_profiles",
  "mauthors": "faculty of computing, universiti teknologi malaysia",
  "api_key": "f2f8a14b58b97ce43b6861d726c878c830513380d64c846423a1814b133b25cb"
}

search = GoogleSearch(params)

data = []

In [ ]:
profiles_is_present = True
while profiles_is_present:

    results = search.get_dict()
    for response in results['profiles']:
    
        data.append({
            'Name': response['name'],
            'Author ID': response['author_id'],
            'Email': response.get('email', 'N/A')
        })
   
    
    # if next page in SerpApi pagination -> update params to new a page results.
    # if no next page -> exit the while loop.
    if "next" in results.get("pagination", []):
        search.params_dict.update(dict(parse_qsl(urlsplit(results.get("pagination").get("next")).query)))
    else:
        profiles_is_present = False

In [ ]:
df = pd.DataFrame(data)
# df.to_csv('google_scholar_data.csv', index=False)
df

                         Name     Author ID                          Email
0        Waleed Al-Rahmi, PhD  jEJuIWAAAAAJ                            N/A
1        Mohd Shahizan Othman  QzgVq24AAAAJ       Verified email at utm.my
2            Dayang NA Jawawi  4zE7K1YAAAAJ       Verified email at utm.my
3    Syed Hamid Hussain Madni  MUUFa60AAAAJ       Verified email at utm.my
4    Bander Ali Saleh Al-rimy  8vIXgG8AAAAJ       Verified email at utm.my
..                        ...           ...                            ...
56  Samira Fotoohifiroozabadi  a1TiuEAAAAAJ                            N/A
57           MOHD AZIM ZAINAL  O6tdLNwAAAAJ  Verified email at uitm.edu.my
58            Syazwa Mad Jais  DvTQ6_cAAAAJ  Verified email at live.utm.my
59     Nurul Raudhah Zulkifli  QCHJR_gAAAAJ                            N/A
60       Zulwaqar Zain Mohtar  Was13OMAAAAJ  Verified email at live.utm.my

[61 rows x 3 columns]

# **Main Assignment**

## Scrape only first page TO BE DELETED

In [ ]:
data = []
for response in results['organic_results']:
    
    data.append({
        'Title': response.get('title', 'N/A'),
        'Link': response.get('link', 'N/A'),
        'Snippet': response.get('snippet', 'N/A'),
        'Resources': response.get('resources', 'N/A'),
        'Publication Info': response.get('publication_info', 'N/A')
    })

In [ ]:
import pandas as pd
df = pd.DataFrame(data)
df

## Scrape any and all pages available for query "faculty of computing, universiti teknologi malaysia"

In [ ]:
from serpapi import GoogleSearch
from urllib.parse import urlsplit, parse_qsl

params = {
  "engine": "google_scholar",
  "q": "faculty of computing, universiti teknologi malaysia", 
  "api_key": "188fcd8d2777f0210b4daa058e9d5b601dcd0725fb043a373b1d468967a4b9e5"
}

search = GoogleSearch(params)
data_foc_utm = []

In [ ]:
profiles_is_present = True
while profiles_is_present:

    results = search.get_dict()
    for response in results['organic_results']:
    
        data_foc_utm.append({
            'Title': response.get('title', 'N/A'),
            'Link': response.get('link', 'N/A'),
            'Snippet': response.get('snippet', 'N/A'),
            'Resources': response.get('resources', 'N/A'),
            'Publication Info': response.get('publication_info', 'N/A')
        })
   
    
    # if next page in SerpApi pagination -> update params to new a page results.
    # if no next page -> exit the while loop.
    if "next" in results.get("pagination", []):
        search.params_dict.update(dict(parse_qsl(urlsplit(results.get("pagination").get("next")).query)))
    else:
        profiles_is_present = False

KeyError: ignored

In [ ]:
import pandas as pd
df_foc_utm = pd.DataFrame(data_foc_utm)
df_foc_utm

,Title,Link,Snippet,Resources,Publication Info
0,Use of e-learning by university students in Ma...,https://ieeexplore.ieee.org/abstract/document/...,… the bachelor’s degree in computer science fr...,"[{'title': 'ieee.org', 'file_format': 'PDF', '...","{'summary': 'WM Al-Rahmi, N Alias, MS Othman, ..."
1,Timetable scheduling system using genetic algo...,https://ijic.utm.my/index.php/ijic/article/vie...,… Abstract—Current timetable scheduling system...,"[{'title': 'utm.my', 'file_format': 'PDF', 'li...","{'summary': 'HK Mammi, LY Ying - International..."
2,The effectiveness of using e-learning in Malay...,https://www.mcser.org/journal/index.php/mjss/a...,… the action of acquiring knowledge through co...,"[{'title': 'mcser.org', 'file_format': 'PDF', ...","{'summary': 'WM Al-Rahmi, MS Othman, LM Yusuf ..."
3,A new algorithm for improving the low contrast...,https://onlinelibrary.wiley.com/doi/abs/10.100...,Contrast is a distinctive visual attribute tha...,N/A,"{'summary': 'Z Al‐Ameen, G Sulong - Scanning, ..."
4,“Faculty of Computer Science and Information S...,https://core.ac.uk/download/pdf/42910251.pdf,"The widespread use of computer applications, d...","[{'title': 'core.ac.uk', 'file_format': 'PDF',...","{'summary': 'S Defit, MNM Sap - core.ac.uk', '..."
...,...,...,...,...,...
975,Sistem Pengurusan Tempahan Produk Berkomputer,N/A,,N/A,{'summary': 'R AB RAHMAN - 2000 - Universiti T...
976,Sistem Pembelajaran Bahasa Inggeris Atas Talia...,N/A,,N/A,{'summary': 'F Nishtar - 2003 - Universiti Tek...
977,Penjanaan Set Soalan Peperiksaan Secara Rawak,N/A,,N/A,{'summary': 'SR ISMAIL - 2005 - Universiti Tek...
978,Pembangunan Prototaip Aplikasi Pelayan Pelangg...,N/A,,N/A,{'summary': 'MY Yasnain - 2000 - Universiti Te...
979,SYSTEM PEMBELAJARAN MATEMATIK (UPSR) MENGGUNAK...,N/A,,N/A,{'summary': 'NM Musa - 2007 - Universiti Tekno...

In [ ]:
df_foc_utm.to_csv('foc_utm.csv', index=False)

In [ ]:
!pip install pymongo
from pymongo import MongoClient

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pymongo in /usr/local/lib/python3.10/dist-packages (4.3.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from pymongo) (2.3.0)

In [ ]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://mikhel:admin@cluster0.kwav8pt.mongodb.net/?retryWrites=true&w=majority"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [ ]:
import csv
import pymongo

# Connect to MongoDB
client = pymongo.MongoClient('mongodb+srv://mikhel:admin@cluster0.kwav8pt.mongodb.net/test')
db = client['GoogleScholar']
collection = db['FacultyOfComputingUTM']

data = df_foc_utm.to_dict(orient='records')
collection.insert_many(data)